name: Java CD with Gradle

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: .env
        run: |
          cd ./
          touch .env
          echo "${{ secrets.VAR }}" >> .env
        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle (without Test)
        run: ./gradlew clean build -x test --stacktrace

      - name: Copy files via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.WAS_HOST }}
          username: ${{ secrets.WAS_USERNAME }}
          key: ${{ secrets.WAS_KEY }}
          port: ${{ secrets.WAS_SSH_PORT }}
          source: "."
          target: "/home/${{ secrets.WAS_USERNAME }}"

      - name: 서버 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WAS_HOST }}
          username: ${{ secrets.WAS_USERNAME }}
          key: ${{ secrets.WAS_KEY }}
          port: ${{ secrets.WAS_SSH_PORT }}
          script: |
            kill -9 $(lsof -t -i:${{ secrets.PORT }})
            nohup java -jar /home/${{ secrets.WAS_USERNAME }}/build/libs/ZoozooClub-0.0.1-SNAPSHOT.jar > mylog.log 2>&1 &